export const CURATED_DSA_TOPICS = [
  { name: 'Arrays', tags: ['Array', 'Arrays'] },
  { name: 'Strings', tags: ['String', 'Strings'] },
  { name: 'Hashing (Map / Set)', tags: ['Hash Table', 'Hash Function', 'Ordered Set', 'Hashing'] },
  { name: 'Two Pointers', tags: ['Two Pointers'] },
  { name: 'Sliding Window', tags: ['Sliding Window'] },
  { name: 'Prefix Sum', tags: ['Prefix Sum'] },
  { name: 'Binary Search', tags: ['Binary Search'] },
  { name: 'Recursion', tags: ['Recursion'] },
  { name: 'Backtracking', tags: ['Backtracking'] },
  { name: 'Linked List', tags: ['Linked List', 'Doubly-Linked List'] },
  { name: 'Stack', tags: ['Stack'] },
  { name: 'Queue', tags: ['Queue', 'Monotonic Queue'] },
  { name: 'Monotonic Stack', tags: ['Monotonic Stack'] },
  {
    name: 'Trees (Binary Tree / BST)',
    tags: ['Tree', 'Binary Tree', 'Binary Search Tree', 'Trie'],
  },
  {
    name: 'Graphs',
    tags: [
      'Graph',
      'Graph Theory',
      'Breadth-First Search',
      'Depth-First Search',
      'Topological Sort',
    ],
  },
  { name: 'Greedy', tags: ['Greedy'] },
  { name: 'Heap / Priority Queue', tags: ['Heap', 'Heap (Priority Queue)'] },
  { name: 'Dynamic Programming (DP)', tags: ['Dynamic Programming', 'Memoization'] },
  { name: 'Bit Manipulation', tags: ['Bit Manipulation', 'Bitmask'] },
  { name: 'Union Find (DSU)', tags: ['Union Find', 'Union-Find', 'Disjoint Set'] },
]
